version: "3.5"
services:
  app:
    build: ./app/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./app/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: